[package]
name = "size"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty-bytes = "0.2.2"
crossbeam-channel = "0.5.1"